<Project>
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildProjectDirectory)\TestResults\coverage\</CoverletOutput>
    <Threshold>70</Threshold>
    <ThresholdType>line</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
    <Include>[ProFootball.Application]*,[ProFootball.Domain]*</Include>
    <Exclude>[ProFootball.Application]ProFootball.Application.Abstractions.*,[ProFootball.Application]ProFootball.Application.Contracts.*</Exclude>
  </PropertyGroup>
</Project>
