// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProFootball.Infrastructure.Persistence;

#nullable disable

namespace ProFootball.Infrastructure.Migrations
{
    [DbContext(typeof(ProFootballDbContext))]
    [Migration("20260418184804_CountryAsTextModel")]
    partial class CountryAsTextModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProFootball.Domain.Entities.FootballClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("football_clubs", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.FootballMatch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamGoal")
                        .HasColumnType("integer");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeTeamApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamGoal")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchApiId")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamApiId");

                    b.HasIndex("CountryName");

                    b.HasIndex("Date");

                    b.HasIndex("HomeTeamApiId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("MatchApiId")
                        .IsUnique();

                    b.HasIndex("Season");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CountryName");

                    b.HasIndex("Name");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlayerApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerFifaApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlayerFifaApiId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.PlayerAttribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AttackingWorkRate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefensiveWorkRate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerFifaApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("Potential")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("OverallRating");

                    b.HasIndex("PlayerApiId");

                    b.HasIndex("Potential");

                    b.HasIndex("PlayerApiId", "Date");

                    b.ToTable("player_attributes", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TeamApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamFifaApiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LongName");

                    b.HasIndex("TeamFifaApiId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.TeamAttribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildUpPlayPassing")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildUpPlaySpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("ChanceCreationPassing")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefencePressure")
                        .HasColumnType("integer");

                    b.Property<int>("TeamApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamFifaApiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TeamApiId");

                    b.HasIndex("TeamApiId", "Date");

                    b.ToTable("team_attributes", (string)null);
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.FootballMatch", b =>
                {
                    b.HasOne("ProFootball.Domain.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.PlayerAttribute", b =>
                {
                    b.HasOne("ProFootball.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerApiId")
                        .HasPrincipalKey("PlayerApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProFootball.Domain.Entities.TeamAttribute", b =>
                {
                    b.HasOne("ProFootball.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamApiId")
                        .HasPrincipalKey("TeamApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
